server:
  port: 8083

spring:
  application:
    name: swallows-core
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false  #开发时关闭缓存，不然没法看到实时页面

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*com/**/mapper.xml
logging:
  level:
    root: info
    com.swallow: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

host:
  swallows:
    admin: http://localhost:8082
