server:
  port: 8086
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JWXYZ/springcouldconfigure/
          search-paths: configures
          password:
          username:
          skip-ssl-validation: true
          label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
