spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    druid:
      initial-size: 5 #连接池大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      username: root
      password: root
